[build]
  # Skip build process and just publish static files
  command = "echo 'Skipping build step, publishing static index.html'"
  publish = "."

[build.environment]
  NODE_VERSION = "20.11.0"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# These redirects are needed for Next.js App Router
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/image-functions/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/.netlify/functions/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/.netlify/functions/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-page"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'" 