"use client"

import * as React from "react"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Wand2, Check, Sparkles } from "lucide-react"

interface PostPreviewProps {
  post: {
    text: string
    image?: string
    hashtags: string[]
  }
  onRefine: () => void
  onApprove: () => void
}

export function PostPreview({ post, onRefine, onApprove }: PostPreviewProps) {
  return (
    <div className="space-y-8">
      <Card className="overflow-hidden gradient-border bg-card/60 backdrop-blur-sm">
        <div className="relative aspect-video w-full overflow-hidden">
          {post.image ? (
            <Image
              src={post.image}
              alt="Generated image"
              fill
              className="object-cover"
            />
          ) : (
            <div className="w-full h-full bg-muted flex items-center justify-center">
              <span className="text-muted-foreground">No image generated</span>
            </div>
          )}
        </div>
        <CardContent className="p-6">
          <div className="space-y-4">
            <div className="space-y-2">
              <h3 className="text-xl font-semibold gradient-text">Caption</h3>
              <p className="text-lg">{post.text}</p>
            </div>
            
            {post.hashtags.length > 0 && (
              <div className="space-y-2">
                <h3 className="text-md font-semibold gradient-text">Hashtags</h3>
                <div className="flex flex-wrap gap-2">
                  {post.hashtags.map((tag) => (
                    <Badge 
                      key={tag} 
                      className="bg-muted/40 hover:bg-primary/20 text-foreground border border-border/40 backdrop-blur-sm"
                    >
                      {tag}
                    </Badge>
                  ))}
                </div>
              </div>
            )}
          </div>
        </CardContent>
        <CardFooter className="flex justify-between py-6 px-6 border-t border-border/40 bg-muted/20">
          <Button 
            variant="outline" 
            onClick={onRefine}
            className="gradient-border bg-muted/40 hover:bg-muted"
          >
            <Wand2 className="mr-2 h-4 w-4 text-primary" />
            Refine
          </Button>
          <Button 
            onClick={onApprove}
            className="gradient-fill text-white"
          >
            <Check className="mr-2 h-4 w-4" />
            Approve
          </Button>
        </CardFooter>
      </Card>
      
      <div className="flex justify-center opacity-90">
        <div className="flex items-center space-x-2 text-muted-foreground text-xs">
          <Sparkles className="h-3 w-3" />
          <span>Generated by AI - Review before posting</span>
        </div>
      </div>
    </div>
  )
}